---

- name: Setup Tier 3
  hosts: tier3
  become: yes

  roles:
    - mysql

  tags:
    - tier3

- name: Setup Tier 2
  hosts: tier2
  become: yes

  roles:
    - php
    - apache
    - wordpress

  tags:
    - tier2

- name: Setup Tier 1
  hosts: tier1
  become: yes

  roles:
    - nginx

  tags:
    - tier1
